site_name: Anvil Docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  extra:
    generator: false
  favicon: img/favicon.ico
  icon:
    logo: img/favicon.ico
