site_name: Anvil Docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  favicon: img/favicon.ico
  logo: img/favicon.ico

extra:
  generator: false
