site_name: Anvil Docs

theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.footer
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false
