---
name: Publish Docs to Github Pages 

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Caching
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install mkdocs-material theme
        run: pip install mkdocs-material

      - name: Install pillow cairosvg
        run: pip install pillow cairosvg

      - name: mkdocs gh-deploy to gh-pages branch
        run: mkdocs gh-deploy --force
